name: visualrl
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy=1.19.2
  - scikit-image=0.18.1
  - nvidia::cudatoolkit=11.1
  - pytorch::pytorch==1.10.0
  - pytorch::torchvision==0.11.0
  - pip:
    - kornia
    - gym==0.22
    - git+https://github.com/deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git@06f7e33
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - mujoco-py<2.2,>=2.1
    - sklearn
    - matplotlib
    - opencv-python==4.5.3.56
    - termcolor
    - numpy<1.24.0